### ISSUE TITLE
What is the function of this plugin and what should I expect of it?

### ISSUE THREAD

**Issue by xinecoulter** [cloudinary/cloudinary_tinymce#3]
1. Does this mean that this plugin allows the user to upload an image to the TinyMCE text editor? What should happen when the user clicks on the image button of the TinyMCE text editor?
   
   > This plugin replaces the image button of TinyMCE to allow you to add and manipulate images from Cloudinary's cloud-based media library. 
2. When following the steps outlined in the documentation, the pop-up that appears after clicking on the image button of the TinyMCE text editor is empty. Does the body of `cloudinaryimage/image.htm` need to be filled with content? Must I include my own form and input, or is this a sign that something went wrong when I tried to set up the plugin?

**Comment by jeffmthomas** [comment]
You don't happen to have an example of how to make this work with php or jQuery, do you?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
