### ISSUE TITLE
IFRAME element is not sized to the popup window

### ISSUE THREAD

**Issue by wshager** [cloudinary/cloudinary_tinymce#4]
When the window opens the IFRAME is too small to see all the options in the CMS intergration page, must importantly the "Insert into post" button.

**Comment by jeffmthomas** [comment]
Was having this issue on both v3 and v4.  I also fixed it by making the html have a height of 100% in `image.htm`

**Comment by MaorGariv** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
