### ISSUE TITLE
TinyMce 4

### ISSUE THREAD

**Issue by AndyNormore** [cloudinary/cloudinary_tinymce#6]
Opening an issue for Cloudinary and TinyMCE 4.

Thank you.

**Comment by roeeba** [comment]
Hi @AndyNormore, this is currently not in our plans for the near future. With that said, I've forwarded your inquiry to our product team to review it further. Thank you for bringing this up.

**Comment by AndyNormore** [comment]
Thanks. Lots of folks Googling for it. <3 Cloudinary.

**Comment by nhuhoai** [comment]
Hey guys, from TinyMCE v4.2, there is a magical param: [images_upload_url](https://www.tinymce.com/docs/advanced/handle-async-image-uploads/) => no more need a plugin.

I've create an example [here](https://github.com/FranicFlow/tinymce-cloudinary-php)

**Comment by idobarnoam** [comment]
Thanks for sharing @nhuhoai!

**Comment by omolojakazeem** [comment]
Please I am finding it difficult to implement saving the images in cloudinary. I actually don't know how to write this function in the image_upload_url

**Comment by roeeba** [comment]
Hi @omolojakazeem , `image_upload_url` is not a Cloudinary function. I found [this page](https://www.programmersought.com/article/11368606547/) on the web, which may help you.
