### ISSUE TITLE
Insert Into Post dissapeared

### ISSUE THREAD

**Issue by edwardteach42** [cloudinary/cloudinary_tinymce#8]
Has the insert into post option been removed from the cloudinary CMS.  It seems as though it has disappeared from the CMS in the last couple of weeks.  Is there a change that needs to be made?

**Comment by d-mendoza** [comment]
Hi,
Are you referring to the Cloudinary WordPress plugin or from using cloudinary-tinymce directly?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
